import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-zinc-950 flex justify-center h-dvh overflow-hidden`}
      >
        <div className="w-full max-w-[430px] h-full bg-[var(--background)] text-[var(--foreground)] shadow-2xl relative overflow-y-auto overflow-x-hidden border-x border-black/5 dark:border-white/5 scrollbar-hide">
          {children}
        </div>
      </body>
    </html>
  );
}
